### ISSUE TITLE
username/password confusion

### ISSUE THREAD

**Issue by 128keaton** [panicinc/PunchClock#27]
Hello, I've setup the PunchClock app successfully locally, and I've tried deploying, but I always get a 401 unauthorized. I've tried my Heroku username, the database username, and my computer username (just threw that one in there). All 401. My url is fine, its my app's. What could be the issue?

**Comment by 128keaton** [comment]
Never mind, just run 'heroku config' in your app's directory to get the required information.

**Comment by foozmeat** [comment]
:+1:

**Comment by 128keaton** [comment]
Lesson learned, dont debug at 2 AM.
